logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: TRACE
spring:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
  liquibase:
    enabled: false
  batch:
    jdbc:
      initialize-schema: always

backbase:
  security:
    public.paths: "/**"
    csrf:
      enabled: false
    mtls:
      enabled: false
  stream:
    cxp:
      privateRepo: false
      auditRepoId: auditFileStorage
      auditRepoName: Audit CSV Files Storage Repository
      storageImpl: DB
      contentServiceUrl: http://contentservices:8080
      serviceId: contentservices
  audit:
    batch:
      export:
        enabled: true
        cronExpression: 0 0/1 * * * ?
        chunkSize: 5000
        batchWriteSize: 1000
        integrityCheck: true
        downloadCheck: true
        daily: true
        params:
          requestId: 1
          retentionDays: 10
      cleanup:
        enabled: true
        chunkSize: 1
        batchWriteSize: 100
      csvRemoval:
        enabled: true
        cronExpression: 0 0/1 * * * ?
        chunkSize: 1000
        batchWriteSize: 100
        params:
          requestId: 1
          exportJobId: 0


